# Generated by Django 6.0.7 on 2026-07-16 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aereo',
            fields=[
                ('codice_icao', models.CharField(db_column='Codice_ICAO', max_length=10, primary_key=True, serialize=False)),
                ('modello', models.CharField(db_column='Modello', max_length=100)),
                ('compagnia', models.CharField(db_column='Compagnia', max_length=100)),
                ('latitudine', models.FloatField(db_column='Latitudine')),
                ('longitudine', models.FloatField(db_column='Longitudine')),
                ('lunghezza', models.FloatField(db_column='Lunghezza')),
                ('altezza', models.FloatField(db_column='Altezza')),
                ('apertura_alare', models.FloatField(db_column='Apertura_alare')),
                ('tipo', models.CharField(db_column='Tipo', max_length=15)),
                ('capacita', models.IntegerField(blank=True, db_column='Capacita', null=True)),
                ('peso_max', models.FloatField(blank=True, db_column='Peso_Max', null=True)),
                ('peso_occupato', models.FloatField(blank=True, db_column='Peso_occupato', null=True)),
                ('volume_occupato', models.FloatField(blank=True, db_column='Volume_occupato', null=True)),
                ('capienza', models.IntegerField(blank=True, db_column='Capienza', null=True)),
                ('numero_gate', models.IntegerField(blank=True, db_column='Numero_gate', null=True)),
                ('terminal_gate', models.CharField(blank=True, db_column='Terminal_gate', max_length=20, null=True)),
            ],
            options={
                'db_table': 'aereo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssistenteDiVolo',
            fields=[
                ('codice_fiscale', models.CharField(db_column='Codice_fiscale', max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cognome', models.CharField(db_column='Cognome', max_length=100)),
                ('data_nascita', models.DateField(db_column='Data_nascita')),
                ('numero_licenza', models.IntegerField(db_column='Numero_licenza', unique=True)),
                ('stipendio', models.DecimalField(db_column='Stipendio', decimal_places=2, max_digits=20)),
                ('data_assunzione', models.DateField(db_column='Data_assunzione')),
                ('valutazione', models.DecimalField(db_column='Valutazione', decimal_places=1, max_digits=2)),
            ],
            options={
                'db_table': 'assistente_di_volo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContainerAereo',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=11, primary_key=True, serialize=False)),
                ('capacita', models.FloatField(db_column='Capacita')),
                ('compagnia_logistica', models.CharField(db_column='Compagnia_logistica', max_length=100)),
                ('peso', models.FloatField(db_column='Peso')),
                ('data_inizio', models.DateField(db_column='Data_inizio')),
                ('data_fine', models.DateField(db_column='Data_fine')),
                ('destinazione', models.CharField(db_column='Destinazione', max_length=100)),
            ],
            options={
                'db_table': 'container_aereo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('pk', models.CompositePrimaryKey('numero', 'terminal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='Numero')),
                ('terminal', models.CharField(db_column='Terminal', max_length=20)),
                ('tipo', models.CharField(db_column='Tipo', max_length=15)),
                ('lunghezza', models.FloatField(db_column='Lunghezza')),
            ],
            options={
                'db_table': 'gate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data_inizio', models.DateField(db_column='Data_inizio')),
                ('data_fine', models.DateField(db_column='Data_fine')),
                ('destinazione', models.CharField(db_column='Destinazione', max_length=100)),
                ('prezzo', models.DecimalField(db_column='Prezzo', decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'itinerario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('pk', models.CompositePrimaryKey('codice_fiscale', 'lingua', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lingua', models.CharField(db_column='Lingua', max_length=50)),
                ('livello', models.CharField(db_column='Livello', max_length=6)),
            ],
            options={
                'db_table': 'lingua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MagazzinoAeroportuale',
            fields=[
                ('pk', models.CompositePrimaryKey('nome', 'posizione', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('posizione', models.CharField(db_column='Posizione', max_length=100)),
                ('tipo', models.CharField(db_column='Tipo', max_length=100)),
                ('capacita', models.FloatField(db_column='Capacita')),
            ],
            options={
                'db_table': 'magazzino_aeroportuale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merce',
            fields=[
                ('sscc', models.CharField(db_column='SSCC', max_length=18, primary_key=True, serialize=False)),
                ('peso', models.FloatField(db_column='Peso')),
                ('paese', models.CharField(db_column='Paese', max_length=50)),
                ('categoria', models.CharField(db_column='Categoria', max_length=100)),
            ],
            options={
                'db_table': 'merce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passeggero',
            fields=[
                ('codice_fiscale', models.CharField(db_column='Codice_fiscale', max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cognome', models.CharField(db_column='Cognome', max_length=100)),
                ('data_nascita', models.DateField(db_column='Data_nascita')),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'passeggero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('pk', models.CompositePrimaryKey('codice_icao', 'numero', blank=True, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='Numero')),
                ('classe', models.CharField(db_column='Classe', max_length=11)),
                ('tipologia', models.CharField(db_column='Tipologia', max_length=10)),
            ],
            options={
                'db_table': 'posto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codice_icao', models.CharField(db_column='Codice_ICAO', max_length=10)),
                ('numero', models.IntegerField(db_column='Numero')),
                ('data_inizio', models.DateField(db_column='Data_inizio')),
                ('scadenza', models.DateField(db_column='Scadenza')),
                ('bagaglio_extra', models.IntegerField(db_column='Bagaglio_extra')),
            ],
            options={
                'db_table': 'prenotazione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scali',
            fields=[
                ('pk', models.CompositePrimaryKey('id_itinerario', 'nome_scalo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nome_scalo', models.CharField(db_column='Nome_scalo', max_length=100)),
            ],
            options={
                'db_table': 'scali',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stoccaggio',
            fields=[
                ('sscc', models.OneToOneField(db_column='SSCC', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aeroporto.merce')),
                ('nome_magazzino', models.CharField(db_column='Nome_magazzino', max_length=100)),
                ('posizione_magazzino', models.CharField(db_column='Posizione_magazzino', max_length=100)),
            ],
            options={
                'db_table': 'stoccaggio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPasseggero',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('passeggero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aeroporto.passeggero')),
            ],
        ),
        migrations.CreateModel(
            name='UserAereo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aereo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeroporto.aereo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'aereo')},
            },
        ),
        migrations.CreateModel(
            name='UserAssistenteDiVolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeroporto.assistentedivolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aeroporto_userassistentedivolo',
                'unique_together': {('user', 'assistente')},
            },
        ),
        migrations.CreateModel(
            name='UserGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gate', models.IntegerField(default=0)),
                ('terminal_gate', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aeroporto_usergate',
                'unique_together': {('user', 'numero_gate', 'terminal_gate')},
            },
        ),
        migrations.CreateModel(
            name='UserItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeroporto.itinerario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aeroporto_useritinerario',
                'unique_together': {('user', 'itinerario')},
            },
        ),
        migrations.CreateModel(
            name='UserMagazzinoAeroportuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_magazzino', models.CharField(default='Magazzino', max_length=100)),
                ('posizione_magazzino', models.CharField(default='Posizione', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aeroporto_usermagazzinoaeroportuale',
                'unique_together': {('user', 'nome_magazzino', 'posizione_magazzino')},
            },
        ),
    ]
