"""
URL configuration for nucleo project.
"""
from django.contrib import admin
from nucleo import views
from django.urls import path

urlpatterns = [
    path('magazzino/aggiungi', views.magazzino_aggiungi, name='magazzino_aggiungi'),
    path('magazzino/modifica/<str:nome>/<str:posizione>', views.magazzino_modifica, name='magazzino_modifica'),
    path('magazzino/elimina/<str:nome>/<str:posizione>', views.magazzino_elimina, name='magazzino_elimina'),
    path('magazzino/stoccaggio/modifica/<str:sscc>', views.stoccaggio_modifica, name='stoccaggio_modifica'),
    path('magazzino/stoccaggio/elimina/<str:sscc>', views.stoccaggio_elimina, name='stoccaggio_elimina'),
    path('magazzino/stoccaggio/<str:nome>/<str:posizione>', views.stoccaggio, name='stoccaggio'),
    path('magazzino/stoccaggio/aggiungi/<str:nome>/<str:posizione>', views.stoccaggio_aggiungi, name='stoccaggio_aggiungi'),
    path('aereo_passeggeri/aggiungi', views.aereo_passeggeri_aggiungi, name='aereo_passeggeri_aggiungi'),
    path('aereo_passeggeri/modifica/<str:codice_icao>', views.aereo_passeggeri_modifica, name='aereo_passeggeri_modifica'),
    path('aereo_passeggeri/elimina/<str:codice_icao>', views.aereo_passeggeri_elimina, name='aereo_passeggeri_elimina'),
    path('aereo_passeggeri/posto/<str:codice_icao>', views.posto, name='posto'),
    path('aereo_passeggeri/posto/aggiungi/<str:codice_icao>', views.posto_aggiungi, name='posto_aggiungi'),
    path('aereo_passeggeri/posto/modifica/<str:codice_icao>/<int:numero>', views.posto_modifica, name='posto_modifica'),
    path('aereo_passeggeri/posto/elimina/<str:codice_icao>/<int:numero>', views.posto_elimina, name='posto_elimina'),
    path('aereo_passeggeri/itinerario', views.itinerario, name='itinerario'),
    path('aereo_passeggeri/itinerario/aggiungi', views.itinerario_aggiungi, name='itinerario_aggiungi'),
    path('aereo_passeggeri/itinerario/modifica/<int:itinerario_id>', views.itinerario_modifica, name='itinerario_modifica'),
    path('aereo_passeggeri/itinerario/elimina/<int:itinerario_id>', views.itinerario_elimina, name='itinerario_elimina'),
    path('aereo_passeggeri/assistente', views.assistente, name='assistente'),
    path('aereo_passeggeri/assistente/aggiungi', views.assistente_aggiungi, name='assistente_aggiungi'),
    path('aereo_passeggeri/assistente/modifica/<str:codice_fiscale>', views.assistente_modifica, name='assistente_modifica'),
    path('aereo_passeggeri/assistente/elimina/<str:codice_fiscale>', views.assistente_elimina, name='assistente_elimina'),
    path('aereo_passeggeri/prenotazione/<str:codice_icao>', views.aereo_prenotazione, name='aereo_prenotazione'),
    path('aereo_merci/aggiungi', views.aereo_merci_aggiungi, name='aereo_merci_aggiungi'),
    path('aereo_merci/modifica/<str:codice_icao>', views.aereo_merci_modifica, name='aereo_merci_modifica'),
    path('aereo_merci/elimina/<str:codice_icao>', views.aereo_merci_elimina, name='aereo_merci_elimina'),
    path('aereo_merci/container/<str:codice_icao>', views.container, name='container'),
    path('aereo_merci/container/aggiungi/<str:codice_icao>', views.container_aggiungi, name='container_aggiungi'),
    path('aereo_merci/container/modifica/<str:container_id>', views.container_modifica, name='container_modifica'),
    path('aereo_merci/container/elimina/<str:container_id>', views.container_elimina, name='container_elimina'),
    path('aereo_merci/merce/<str:container_id>', views.merce, name='merce'),
    path('aereo_merci/merce/aggiungi/<str:container_id>', views.merce_aggiungi, name='merce_aggiungi'),
    path('aereo_merci/merce/modifica/<str:sscc>', views.merce_modifica, name='merce_modifica'),
    path('aereo_merci/merce/elimina/<str:sscc>', views.merce_elimina, name='merce_elimina'),
    path('gate/aggiungi', views.gate_aggiungi, name='gate_aggiungi'),
    path('gate/modifica/<int:numero>/<str:terminal>', views.gate_modifica, name='gate_modifica'),
    path('gate/elimina/<int:numero>/<str:terminal>', views.gate_elimina, name='gate_elimina'),
    path('gate/assegnazione', views.assegnazione, name='assegnazione'),
    path('gate/assegnazione/visualizza', views.assegnazione_visualizza, name='assegnazione_visualizza'),
    path('passeggero/aggiungi', views.passeggero_aggiungi, name='passeggero_aggiungi'),
    path('passeggero/modifica', views.passeggero_modifica, name='passeggero_modifica'),
    path('passeggero/elimina', views.passeggero_elimina, name='passeggero_elimina'),
    path('passeggero/visualizza', views.passeggero_visualizza, name='passeggero_visualizza'),
    path('passeggero/prenotazione', views.prenotazione, name='prenotazione'),
    path('passeggero/prenotazione/aggiungi/<str:codice_icao>/<int:numero>', views.prenotazione_aggiungi, name='prenotazione_aggiungi'),
    path('passeggero/prenotazione/visualizza', views.prenotazione_visualizza, name='prenotazione_visualizza'),
    path('passeggero/prenotazione/modifica/<int:id_prenotazione>', views.prenotazione_modifica, name='prenotazione_modifica'),
    path('passeggero/prenotazione/elimina/<int:id_prenotazione>', views.prenotazione_elimina, name='prenotazione_elimina'),
    path('admin/', admin.site.urls),
    path('', views.register, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('modifica_password', views.modifica_password, name='modifica_password'),
    path('error', views.error, name='error'),
    path('passeggero', views.passeggero, name='passeggero'),
    path('gate', views.gate, name='gate'),
    path('aereo_merci', views.aereo_merci, name='aereo_merci'),
    path('aereo_passeggeri', views.aereo_passeggeri, name='aereo_passeggeri'),
    path('magazzino', views.magazzino, name='magazzino'),
]